"""
Location constants for Lucena City, Quezon
"""

LUCENA_BARANGAYS = [
    "Barangay 1",
    "Barangay 2",
    "Barangay 3",
    "Barangay 4",
    "Barangay 5",
    "Barangay 6",
    "Barangay 7",
    "Barangay 8",
    "Barangay 9",
    "Barangay 10",
    "Barangay 11",
    "Barangay 12",
    "Barangay 13",
    "Barangay 14",
    "Barangay 15",
    "Barangay 16",
    "Barangay 17",
    "Barangay 18",
    "Barangay 19",
    "Barangay 20",
    "Barangay 21",
    "Barangay 22",
    "Barangay 23",
    "Barangay 24",
    "Barangay 25",
    "Barangay 26",
    "Barangay 27",
    "Barangay 28",
    "Barangay 29",
    "Barangay 30",
    "Barangay 31",
    "Barangay 32",
    "Barangay 33",
    "Barangay 34",
    "Barangay 35",
    "Barangay 36",
    "Barangay 37",
    "Barangay 38",
    "Barangay 39",
    "Barangay 40",
    "Barangay 41",
    "Barangay 42",
    "Barangay 43",
    "Barangay 44",
    "Barangay 45",
    "Barangay 46",
    "Barangay 47",
    "Barangay 48",
    "Barangay 49",
    "Barangay 50",
    "Barangay 51",
    "Barangay 52",
    "Barangay 53",
    "Barangay 54",
    "Barangay 55",
    "Barangay 56",
    "Barangay 57",
    "Barangay 58",
    "Barangay 59",
    "Barangay 60",
    "Barangay 61",
    "Barangay 62",
    "Barangay 63",
    "Barangay 64",
    "Barangay Bocohan",
    "Barangay Dalahican",
    "Barangay Gulang-Gulang",
    "Barangay Ibabang Dupay",
    "Barangay Ilayang Dupay",
    "Barangay Isabang",
    "Barangay Market View",
    "Barangay Mayao Kanluran",
    "Barangay Mayao Castillo",
    "Barangay Mayao Crossing",
    "Barangay Ransohan",
    "Barangay Salinas",
    "Barangay Talao-Talao",
]

_NORMALIZED_BARANGAYS = {barangay.strip().lower() for barangay in LUCENA_BARANGAYS}

def get_location_choices() -> list[str]:
    """Returns list of valid locations in Lucena City"""
    return LUCENA_BARANGAYS

def is_valid_location(location: str) -> bool:
    """Validates if the given location is a valid barangay in Lucena City"""
    return location.strip().lower() in _NORMALIZED_BARANGAYS
